optimizer:
  class_name: "Adam"
  params:
    lr: 0.0003
scheduler:
  class_name: "MultiStepLR"
  params:
    gamma: 0.5
    milestones:
      - 30
      - 45
id: lr${optim.optimizer.lr}_Multstp${optim.scheduler.params.gamma}
