optimizer:
  class_name: "Adam"
  params:
    lr: 0.0001
scheduler:
  class_name: "MultiStepLR"
  params:
    gamma: 0.3
    milestones:
      - 8
      - 12
id: lr${optim.optimizer.lr}_Multstp${optim.scheduler.params.gamma}
