logging_level: INFO
params:
  gpus: 1
  max_epochs: 60
  limit_val_batches: 1
  log_every_n_steps: 5
  check_val_every_n_epoch: 1
  flush_logs_every_n_steps: 10
  weights_summary: null
  deterministic: False
  benchmark: True
  profiler: "simple"
